config/routes.rb
Bluadmin::Application.routes.draw do  
  captcha_route
  mount StripeEvent::Engine => '/stripe'
  
  namespace :admin do
    resources :users, only: [:index]
    get "send_to_reset_password_email/:id" => "users#send_to_reset_password_email", as: 'send_to_reset_password_email'
    get "setting"             => "users#setting"
    post "new_item"           => "users#new_item"
    match "update_option"     => 'users#update_setting_option',        via: [:post, :patch]
    delete "delete_items/:id"     => "users#delete_items", as: "delete_items"
    
  end
  
  get 'home/index'
  get 'home/about'
  match 'home/contact'             => 'home#contact',        via: [:get, :post]
  get 'home/features'
  get 'home/pricing'

  resources :expenses
  resources :payment_profiles
  resources :projects  
  get 'projects/make_live/:id'                  => 'projects#make_live',   as: 'make_live'

  resources :individual_projects
  get "get_year_data"                           => 'individual_projects#get_year_data'
  get "get_year_bulk_data"                      => 'individual_projects#get_year_bulk_data'

  resources :accounts
  resources :articles
  resources :keywords 
  resources :tasks

  resources :attach_files, only:[:create, :destroy]

  post 'tasks/mark_as_complete/:id'             => 'tasks#mark_as_complete', as: 'mark_as_complete'
  post 'tasks/mark_as_uncomplete/:id'           => 'tasks#mark_as_uncomplete', as: 'mark_as_uncomplete'
  post 'add_new_owner'                          => 'tasks#add_new_owner', as: 'add_new_owner'

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }

  get 'users/index'
  get 'users/setting'

  post 'users/add_card'
  delete 'users/destroy'          => 'users#destroy'
  match 'user/update'             => 'users#update',        via: [:post, :patch]
  
  get 'user/pricing/:id'          => 'users#pricing',       as: 'user_pricing'
  post 'user/purchase'            => 'users#purchase'
  get 'user/thanks'               => 'users#thanks'
  get 'user/money_converting'     => 'users#money_converting'

  post '/tinymce_assets' => 'projects#upload_image'
  
  post '/home/set_option'         => 'home#set_option'

  resources :init_projects
  post '/projects/import_csv'     => 'init_projects#import_csv'
  
  root to: 'home#index'
end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

	# mount_uploader :attach, TaskAttachUploader

  field :name,								type: String  
  field :duration,         		type: String
  field :start_date,          type: Date
  field :end_date,            type: Date  
  field :description,         type: String  
  field :attach,					    type: String

  field :completed,           type: Boolean,      default: false
  field :owners_name,         type: String
  
  field :attach_file_ids,     type: String

  belongs_to :owner
  belongs_to :project
  validates_presence_of :project_id, :name, :start_date, :end_date
  
  validate :end_date_validate

  def user
    project.present? ? project.user : nil
  end
  def attach_files
    if attach_file_ids.present?
      ids = attach_file_ids.split(",")
      AttachFile.in(id:ids)
    else
      []
    end
  end
  def owner_name
    if owner.present?
      owner.name
    else
      owners_name
    end
  end

  def attach_url
    host = ""
    if attach.url.nil?
      "none_image"
    else
      if Rails.env.production?
        attach.url
      else
        attach.url.gsub("#{Rails.root.to_s}/public/", "/")
      end
    end
  end

  private  
  def end_date_validate
    if start_date > end_date
      errors.add(:end_date, "wrong, end_date should not be large than start_date ")
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  def index
    limit = params[:page_limit].present? ? params[:page_limit].to_i : 10
    @tasks = current_user.tasks.paginate(page: params[:page], :per_page => limit)    
    if params[:fid].present?
      ids = params[:fid].chop!
      afs = AttachFile.in(id:ids.split(","))
      afs.destroy_all
    end
  end

  def new
    @task = Task.new
  end
  def create    
    st_dt = DateTime.strptime(params[:task][:start_date], "%d/%m/%Y")
    ed_dt = st_dt + params[:task][:duration].to_i.days    
    params[:task][:end_date] = ed_dt.strftime("%Y-%m-%d")
    @task = Task.new(params[:task].permit(:project_id, :name, :description, :owner, :duration, :start_date, :end_date))
    @task.attach_file_ids = params[:attach_files].join(",") if params[:attach_files].present?
    project = @task.project
    respond_to do |format|
      if @task.save
        UserMailer.assigned_onwer(@task.owner, @task).deliver
        if params[:task][:p_id].present?
          format.html { redirect_to edit_individual_project_path(project) + "?task_page=1"}
        else
          format.html { redirect_to action: :index }
        end        
        format.json { render json: @task, status: :created, location: @task}
        flash[:success] = 'New task was created successfully'
      else
        format.html { render action: :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end      
    end
  end

  def edit
    @task = Task.find(params[:id])
  end
  def update    
    @task = Task.find(params[:id])
    project = @task.project #Project.find(params[:task][:project_id])
    st_dt = DateTime.strptime(params[:task][:start_date], "%d/%m/%Y")
    ed_dt = st_dt + params[:task][:duration].to_i.days    
    params[:task][:end_date] = ed_dt.strftime("%Y-%m-%d")
    
    respond_to do |format|
      if @task.update_attributes(params[:task].permit(:name, :description, :owner, :duration, :start_date, :end_date))
        @task.update_attribute(:attach_file_ids, params[:attach_files].join(",")) if params[:attach_files].present?
        UserMailer.assigned_onwer(@task.owner, @task).deliver
        if params[:task][:p_id].present?
          format.html { redirect_to edit_individual_project_path(project)+"?task_page=1"}
        else
          format.html { redirect_to action: :index }
        end
        format.json { render json: @task, status: :updated, location: @task}
        flash[:success] = 'Task was updated successfully'
      else
        format.html { redirect_to request.referer }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @task = Task.find(params[:id])
  end


  def mark_as_complete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed, true)
    redirect_to edit_individual_project_path(@task.project)
  end

  def mark_as_uncomplete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed, false)
    redirect_to edit_individual_project_path(@task.project)
  end

  def add_new_owner
    owner = current_user.owners.build(params[:owner].permit(:name, :email))
    if owner.save
      # UserMailer.adde_new_onwer(owner).deliver
      data = {:success => [owner.id.to_s, owner.name]}
    else
      data = {:failure => owner.errors.messages.to_json}
    end
    render :json => data
  end

  def destroy    
    @task = Task.find(params[:id])
    @task.destroy
    if params[:pid].present?
      redirect_to edit_individual_project_path(params[:pid]) + "?task_page=1" if @task.destroy
    else
      redirect_to action: :index
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task, html:{class: "form-horizontal"} do |f|
  = f.hidden_field :p_id, {value:params[:pid]}
  - f.object.errors.messages.each do |msg|
    .alert.alert-error= msg.join(' is ')
  
  .row
    .col-md-10
      .form-group
        .col-md-2
          %label *Task Name
        .col-md-10
          = f.text_field :name, required: true, autofocus: true, placeholder: "", class: 'form-control'
      .form-group
        .col-md-2
          %label Description
        .col-md-10
          = f.text_area :description, required: false, placeholder: "", class: 'form-control tinymce'
      .col-md-7
        .form-group
          .col-md-4
            %label *Site Code:
          .col-md-4
            - if f.object.project_id.present?
              %label= f.object.project.site_code
            - else
              = f.select :project_id, options_from_collection_for_select(current_user.live_projects.all, :id, :site_code, selected: params[:pid]), {}, {class: 'form-control', required: true}      
        .form-group
          .col-md-4
            %label *Owner
          .col-md-4
            = f.select :owner, options_from_collection_for_select(current_user.owners, "id", "name"), {prompt: "Select Owner"}, {class: 'form-control', required: true}
          .col-md-2
            = link_to "Add Owner", "#", class:"btn btn-default", :"data-toggle" => "modal", :"data-target" => "#modal_add_new_owner"
        .form-group
          .col-md-4
            %label Duration(Days)
          .col-md-4
            = f.number_field :duration, required: false, placeholder: "", class: 'form-control'
        .form-group
          .col-md-4
            %label Start Date
          .col-md-4
            .input-group.date
              = f.text_field :start_date, value:f.object.start_date.present? ? f.object.start_date.strftime("%d/%m/%Y") : "", class: 'form-control', style:'padding-right: 0px;', required: true
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        / .form-group
        /   .col-md-4
        /     %label End Date
        /   .col-md-6          
        /     .input-group.date
        /       = f.text_field :end_date, value:f.object.end_date.present? ? f.object.end_date.strftime("%d/%m/%Y") : "", class: 'form-control', required: true
        /       %span.input-group-addon
        /         %span.glyphicon.glyphicon-calendar
      .col-md-5
        %label Attach Documents
        .row.attached-files-box
          - f.object.attach_files.each do |file|
            .row{style:"margin-left: 20px;"}
              .col-md-7
                = hidden_field_tag :attach_files, file.id.to_s, name:"attach_files[]"
                %label.file-name= file.read_attribute(:file)
              .col-md-5
                = link_to "X", "javascript://", :"data-url" => attach_file_path(file), class: 'btn-default btn-sm btn-file-close-btn'
        .row.attach-upload-form
          .col-md-7
            = file_field_tag :attach_file, required:false, :onchange =>"validateFiles(this);"
          .col-md-5.upload-button-group{style:'display: none;'}
            = link_to "Upload", "javascript://", class: 'btn btn-primary btn-sm btn-file-upload-btn'
            = link_to "Cancel", "javascript://", class: 'btn btn-danger btn-sm btn-file-cancel-btn'

  .row
    .form-group
      .col-xs-4
        *Required fields
      .col-xs-2
        = f.submit "Save", class: 'btn btn-primary col-xs-8'
      - if Task.where(id:@task.id).first.present? and !Task.where(id:@task.id).first.completed
        .col-xs-2
          = link_to "Mark as Complete", mark_as_complete_path(@task), method: :post, data: {confirm: "Are you sure"}, class: 'btn btn-default'
      - elsif Task.where(id:@task.id).first.present? and Task.where(id:@task.id).first.completed
        .col-xs-2
          = link_to "Mark as UnComplete", mark_as_uncomplete_path(@task), method: :post, data: {confirm: "Are you sure"}, class: 'btn btn-default'
      .col-xs-offset-0.col-xs-2
        - if params[:pid].present?
          = link_to "Cancel", edit_individual_project_path(@task.project.present? ? @task.project.id.to_s : params[:pid] )+"?fid=", class: 'btn btn-default col-xs-8 cancel-task-path'
        - else
          = link_to "Cancel", tasks_path+"?fid=", class: 'btn btn-default col-xs-8 cancel-task-path'


#modal_add_new_owner.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    = form_for :owner, url: add_new_owner_path, method: :post, remote: true, html:{class: "form-horizontal add_new_owner_form"} do |f|
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4#myModalLabel.modal-title Add New owner
        .modal-body.form-horizontal          
          .container
            .col-sm-5
              %fieldset
                .form-group
                  %label.col-sm-4.control-label{for: "title"} *Name
                  .col-sm-8
                    = f.text_field :name, required: true, class: "form-control"
                .form-group
                  %label.col-sm-4.control-label{for: "lastname"}  *Email
                  .col-sm-8
                    = f.email_field :email, required: true, class: "form-control"
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          = f.submit "Add", class: 'btn btn-primary'



:javascript
  $(".add_new_owner_form").on('ajax:success',function(event, data, status, xhr){
    if(data.success){
      $("#task_owner")[0].options.add(new Option(data.success[1], data.success[0]))
      alert("Added new owner");
      $("#modal_add_new_owner").modal('hide');
    }else{
      alert(data.failure)
    }
  });


  function validateFiles(inputFile) {
    var maxExceededMessage = "This file exceeds the maximum allowed file size (5 MB)";
    var extErrorMessage = "Please check the file extension list \ndoc, docx, dotx, xls, xlt, xlsx, xltx, pptx, pptm, potx, ppt, pot, pps, psx, sldx, pdf, jpg, jpeg, gif, png, ods, fods, odp, fodp, odg, fodg, csv";
    var allowedExtension = ["doc", "docx", "dotx", "xls", "xlt", "xlsx", "xltx", "pptx", "pptm", "potx", "ppt", "pot", "pps", "psx", "sldx", "pdf", "jpg",  "jpeg",  "gif",  "png", "BMP", "JPEG", "JPG", "PSD", "GIF", "TIF", "TIFF", "ods", "fods", "odp", "fodp", "odg", "fodg", "csv"]
   
    var extName;
    var maxFileSize = $(inputFile).data('max-file-size');
    var sizeExceeded = false;
    var extError = false;
   
    $.each(inputFile.files, function() {
      if (this.size && maxFileSize && this.size > parseInt(maxFileSize)) {sizeExceeded=true;};
      extName = this.name.split('.').pop();
      if ($.inArray(extName, allowedExtension) == -1) {extError=true;};
    });
    if (sizeExceeded) {
      window.alert(maxExceededMessage);
      $(inputFile).val('');
    };
   
    if (extError) {
      window.alert(extErrorMessage);
      $(inputFile).val('');
    };

    if (!sizeExceeded && !extError){    
      $(".upload-button-group").show();
    }
  }


  $(".btn-file-upload-btn").click(function(){
    data = new FormData();
    jQuery.each($('#attach_file')[0].files, function(i, file) {
        data.append('file', file);
    });    
    $.ajax({
      url: '/attach_files',
      data: data,
      cache: false,
      contentType: false,
      processData: false,
      type: 'POST',
      success: function(data){
        data = jQuery.parseJSON(data);
        row = '<div class="row" style="margin-left: 20px;"><div class="col-md-7"><input id="attach_files" type="hidden" value="'+data.id+'" name="attach_files[]"><label class="file-name">'+data.name+'</label></div><div class="col-md-5"><a href="javascript://" data-url="'+data.delete_url+'" class="btn-default btn-sm btn-file-close-btn">X</a></div></div>'
        $(row).appendTo(".attached-files-box");
        $(".upload-button-group").hide();
        $("#attach_file").val('');
        href = $(".cancel-task-path").attr('href')
        href = href +data.id+ ','
        $(".cancel-task-path").attr('href', href)
      },
      error:function(request, textStatus, errorThrown) {
        msg = JSON.parse(request.responseText)
        var message = (request.status == 422) ? msg.errors : "An unknown error occurred. Support has been contacted.";
        alert(message);
      }
    });
  });

  $(".btn-file-cancel-btn").click(function(){
    $(".upload-button-group").hide();
    $("#attach_file").val('');
  })


  $('.attached-files-box').on('click', '.btn-file-close-btn', function(){
    $.ajax({
      url: $(this).data("url"),
      data: 'data',
      type: 'DELETE',
      done: function(data){      
        $(this).parent().parent().remove();
      }      
    });
    $(this).parent().parent().remove();
  })
  

app/views/tasks/edit.html.haml
.row.edit-task
  %h1.form-title Edit Task
  = render "form"

app/views/tasks/index.html.haml
.row.tasks-list  
  .row
    .col-md-10
      %h1.form-title Tasks
    .col-md-2{style:'margin-top:26px;'}
      = link_to "Add Task", new_task_path, class: 'btn btn-primary', :"data-no-turbolink"=>true
  .col-md-12
    .row
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th Task Name
            %th SiteCode
            %th Duration
            %th Start Date
            %th End Date
            %th Owner
            %th Mange
        %tbody
          - @tasks.each do |task|
            %tr
              %td
                = link_to task.name, task_path(task)
              %td= task.project.site_code
              %td= task.duration
              %td= task.start_date.strftime("%d/%m/%Y")
              %td= task.end_date.strftime("%d/%m/%Y")
              %td= task.owner_name
              %td
                = link_to(edit_task_path(task), class: 'btn-mini', :"data-no-turbolink"=>true) do
                  %i.glyphicon.glyphicon-pencil
                = link_to(task_path(task), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                  %i.glyphicon.glyphicon-trash 
        %tfooter
          %tr
  / .col-md-2
  /   %label 
  /     = DateTime.now.year
  /     Budget Available for this year of budget Allocated

app/views/tasks/new.html.haml
.row.add-new-task
  %h1.form-title Add New Task
  = render "form"

app/views/tasks/show.html.haml
.row
  .col-md-6
    .row.description
      %h3 Description
      = raw @task.description
    .row
      %h3 Uploaded Files
      - @task.attach_files.each do |file|
        .col-md-6
          =link_to file.read_attribute(:file), file.attach_url
        .col-md-4
          Size:
          = file.file_size
          KB
        %br/

  .col-md-4.col-md-offset-1
    .row
      %h3 Site Code : 
      %h5= @task.project.site_code
    .row
      %h3 Name
      %h5= @task.name
    .row
      %h3 Owner
      %h5= @task.owner_name
    .row
      %h3 Duration
      %h5= @task.duration
    .row
      %h3 Start Date
      %h5= @task.start_date.strftime("%d/%m/%Y")
    .row
      %h3 Due Date
      %h5= @task.end_date.strftime("%d/%m/%Y")
.row
  .col-md-2.col-md-offset-3
    = link_to "Edit", edit_task_path(@task), class: 'btn btn-primary col-md-10', :"data-no-turbolink"=>true    
  .col-md-2
    = link_to "Cancel", tasks_path, class: 'btn btn-default col-md-10'
%br/


:javascript
  $(".description img").each(function(){
    parent = $(this).parent();
    src = $(this).attr("src");
    link = "<a href="+src+" target='_blank'><img width='100' height='100' src='"+src+"'></a>"
    parent.append(link);
    $(this).remove();
  })