config/routes.rb
Bluadmin::Application.routes.draw do  
  captcha_route
  mount StripeEvent::Engine => '/stripe'
  
  namespace :admin do
    resources :users, only: [:index]
    get "send_to_reset_password_email/:id" => "users#send_to_reset_password_email", as: 'send_to_reset_password_email'
    get "setting"             => "users#setting"
    post "new_item"           => "users#new_item"
    match "update_option"     => 'users#update_setting_option',        via: [:post, :patch]
    delete "delete_items/:id"     => "users#delete_items", as: "delete_items"
    
  end
  
  get 'home/index'
  get 'home/about'
  match 'home/contact'             => 'home#contact',        via: [:get, :post]
  get 'home/features'
  get 'home/pricing'

  resources :expenses
  resources :payment_profiles
  resources :projects  
  get 'projects/make_live/:id'                  => 'projects#make_live',   as: 'make_live'

  resources :individual_projects
  get "get_year_data"                           => 'individual_projects#get_year_data'
  get "get_year_bulk_data"                      => 'individual_projects#get_year_bulk_data'

  resources :accounts
  resources :articles
  resources :keywords 
  resources :tasks

  resources :attach_files, only:[:create, :destroy]

  post 'tasks/mark_as_complete/:id'             => 'tasks#mark_as_complete', as: 'mark_as_complete'
  post 'tasks/mark_as_uncomplete/:id'           => 'tasks#mark_as_uncomplete', as: 'mark_as_uncomplete'
  post 'add_new_owner'                          => 'tasks#add_new_owner', as: 'add_new_owner'

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }

  get 'users/index'
  get 'users/setting'

  post 'users/add_card'
  delete 'users/destroy'          => 'users#destroy'
  match 'user/update'             => 'users#update',        via: [:post, :patch]
  
  get 'user/pricing/:id'          => 'users#pricing',       as: 'user_pricing'
  post 'user/purchase'            => 'users#purchase'
  get 'user/thanks'               => 'users#thanks'
  get 'user/money_converting'     => 'users#money_converting'

  post '/tinymce_assets' => 'projects#upload_image'
  
  post '/home/set_option'         => 'home#set_option'

  resources :init_projects
  post '/projects/import_csv'     => 'init_projects#import_csv'
  
  root to: 'home#index'
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name,                type: String

  field :pri_key,             type: String
  field :sec_key,             type: String

  field :lsi,                 type: String

  validates_presence_of :project_id, :name

  belongs_to :project
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!
  def index
    limit = params[:page_limit].present? ? params[:page_limit].to_i : 10
    @articles = current_user.articles.paginate(page: params[:page], :per_page => limit)
    @keywords = current_user.keywords.paginate(page: params[:page], :per_page => limit)
  end
  
  def new
    @article = Article.new    
  end
  
  def create
    project = Project.find(params[:article][:project_id])
    @article = project.articles.build(params[:article].permit(:name, :pri_key, :sec_key, :lsi))
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_individual_project_path(project)+"?article_page=1"}
        format.json { render json: @article, status: :created, location: @article}
        flash[:notice] = 'New Article was created successfully'
      else
        format.html { render action: :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end      
    end
  end

  def edit
    @article = Article.find(params[:id])
  end
  def update    
    @article = Article.find(params[:id])
    project = @article.project #Project.find(params[:article][:project_id])
    respond_to do |format|
      if @article.update_attributes(params[:article].permit(:name, :pri_key, :sec_key, :lsi))
        format.html { redirect_to edit_individual_project_path(project)+"?article_page=1"}
        format.json { render json: @article, status: :updated, location: @article}
        flash[:notice] = 'Article was updated successfully'
      else
        format.html { redirect_to request.referer }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to edit_individual_project_path(params[:pid]) if @article.destroy
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article, html:{class: "form-horizontal"} do |f|
  = f.hidden_field :project_id, {value:params[:pid]}
  - f.object.errors.messages.each do |msg|
    .alert.alert-error= msg.join(' is ')
  
  .row
    .col-md-8
      .form-group
        .col-md-4
          %label Site Code:
        .col-md-4
          - if f.object.project_id.present?
            %label= f.object.project.site_code
          - else
            = f.select :project_id, options_from_collection_for_select(current_user.live_projects.all, :id, :site_code, selected:params[:pid]), {}, {class: 'form-control'}
      .form-group
        .col-md-4
          %label *Article Name
        .col-md-4
          = f.text_field :name, required: true, autofocus: true, placeholder: "", class: 'form-control'
      .form-group
        .col-md-4
          %label *Primary Keyword
        .col-md-4
          = f.text_field :pri_key, required: true, placeholder: "", class: 'form-control'
      .form-group
        .col-md-4
          %label *Second Keyword
        .col-md-4
          = f.text_field :sec_key, required: true, placeholder: "", class: 'form-control'
      .form-group
        .col-md-4
          %label LSI
        .col-md-4          
          = f.text_field :lsi, required: false, placeholder: "", class: 'form-control'
          
      
  .row
    .form-group
      .col-xs-3
        *Required fields
      .col-xs-2
        = f.submit "Save", class: 'btn btn-primary col-xs-8'
      .col-xs-offset-0.col-xs-2
        - if params[:pid].present? or @article.project.present?
          = link_to "Cancel", edit_individual_project_path(@article.project.present? ? @article.project.id.to_s : params[:pid] ) + "?article_page=1", class: 'btn btn-default col-xs-8'
        - else
          = link_to "Cancel", articles_path, class: 'btn btn-default col-xs-8'

app/views/articles/edit.html.haml
.row.edit-account
  %h1.form-title Edit Article
  = render "form"

app/views/articles/index.html.haml
.row
  .col-xs-4.text-center
    %h5 Idears
  .col-xs-4.text-center
    
  .col-xs-2
    = link_to "Add Article", new_article_path, class: 'btn btn-primary'
%br/
.row
  .col-xs-10
    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th Number
            %th Site Code
            %th Article Name
            %th Primary Article Keyword
            %th Secondary Article Keyword
            %th LSI
            %th Completed
            %th Manage
        %tbody
          - @articles.each_with_index do |article, i|
            %tr
              %td= i + 1
              %td= article.project.site_code
              %td= article.name
              %td= article.pri_key
              %td= article.sec_key
              %td= article.lsi
              %td
              %td
                = link_to(edit_article_path(article), class: 'btn-mini') do
                  %i.glyphicon.glyphicon-pencil
                = link_to(article_path(article), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                  %i.glyphicon.glyphicon-trash 
        %tfoot
          %tr
            %td.digg_pagination{colspan:8}
              = will_paginate @articles, previous_label: '< PREV', next_label: 'NEXT >' if @articles.present?
%br/
.row
  .col-xs-10.text-center
    %h3 Future Keywords
  .col-xs-2    
    = link_to "Add Keyword", new_keyword_path, class: 'btn btn-primary'
%br/
.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th Pri Keyword
            %th Sec Keyword
            %th Pri Keyword Difficulty
            %th Sec Keyword Difficulty
            %th Pri Monthly Searches
            %th Sec Monthly Searches
            %th Mange
        %tbody
          - @keywords.each do |key|
            %tr
              %td= key.pri_key
              %td= key.sec_key
              %td= key.pri_key_difficult
              %td= key.sec_key_difficult
              %td= key.pri_key_monthly
              %td= key.sec_key_monthly
              %td
                = link_to(edit_keyword_path(key), class: 'btn-mini') do
                  %i.glyphicon.glyphicon-pencil
                = link_to(keyword_path(key), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                  %i.glyphicon.glyphicon-trash 
        %tfoot
          %tr
            %td.digg_pagination{colspan:7}
              = will_paginate @keywords, previous_label: '< PREV', next_label: 'NEXT >' if @keywords.present?

app/views/articles/new.html.haml
.row.add-new-article
  %h1.form-title Add New Article
  = render "form"