config/routes.rb
Bluadmin::Application.routes.draw do  
  captcha_route
  mount StripeEvent::Engine => '/stripe'
  
  namespace :admin do
    resources :users, only: [:index]
    get "send_to_reset_password_email/:id" => "users#send_to_reset_password_email", as: 'send_to_reset_password_email'
    get "setting"             => "users#setting"
    post "new_item"           => "users#new_item"
    match "update_option"     => 'users#update_setting_option',        via: [:post, :patch]
    delete "delete_items/:id"     => "users#delete_items", as: "delete_items"
    
  end
  
  get 'home/index'
  get 'home/about'
  match 'home/contact'             => 'home#contact',        via: [:get, :post]
  get 'home/features'
  get 'home/pricing'

  resources :expenses
  resources :payment_profiles
  resources :projects  
  get 'projects/make_live/:id'                  => 'projects#make_live',   as: 'make_live'

  resources :individual_projects
  get "get_year_data"                           => 'individual_projects#get_year_data'
  get "get_year_bulk_data"                      => 'individual_projects#get_year_bulk_data'

  resources :accounts
  resources :articles
  resources :keywords 
  resources :tasks

  resources :attach_files, only:[:create, :destroy]

  post 'tasks/mark_as_complete/:id'             => 'tasks#mark_as_complete', as: 'mark_as_complete'
  post 'tasks/mark_as_uncomplete/:id'           => 'tasks#mark_as_uncomplete', as: 'mark_as_uncomplete'
  post 'add_new_owner'                          => 'tasks#add_new_owner', as: 'add_new_owner'

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }

  get 'users/index'
  get 'users/setting'

  post 'users/add_card'
  delete 'users/destroy'          => 'users#destroy'
  match 'user/update'             => 'users#update',        via: [:post, :patch]
  
  get 'user/pricing/:id'          => 'users#pricing',       as: 'user_pricing'
  post 'user/purchase'            => 'users#purchase'
  get 'user/thanks'               => 'users#thanks'
  get 'user/money_converting'     => 'users#money_converting'

  post '/tinymce_assets' => 'projects#upload_image'
  
  post '/home/set_option'         => 'home#set_option'

  resources :init_projects
  post '/projects/import_csv'     => 'init_projects#import_csv'
  
  root to: 'home#index'
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController    
  before_filter :authenticate_admin
  
  def index    
    @users = User.all.paginate(page: params[:page], :per_page => 15)
  end


  def send_to_reset_password_email
    @user = User.find(params[:id])
    UserMailer.reset_password(@user).deliver
    flash[:notice] = "Sent the reset password email successfully"
    redirect_to action: :index
  end

  def setting    
  end

  def new_item
    type = params[:new_object]
    item = params[:item]
    case type
    when '0'
      option = Option.create_by_option_name(:project_types)
      opt_val = option.option_value.split(",")
      opt_val << item
      option.update_attribute(:option_value, opt_val.join(","))
    when '1'
      option = Option.create_by_option_name(:moneitions)
      opt_val = option.option_value.split(",")
      opt_val << item
      option.update_attribute(:option_value, opt_val.join(","))
    when '2'
      option = Option.create_by_option_name(:expense_items)
      opt_val = option.option_value.split(",")
      opt_val << item
      option.update_attribute(:option_value, opt_val.join(","))
    when '3'
      option = Option.create_by_option_name(:expense_payments)
      opt_val = option.option_value.split(",")
      opt_val << item
      option.update_attribute(:option_value, opt_val.join(","))
    end
    redirect_to action: :setting
  end
  def update_setting_option
    type = params[:update_object]
    item_number = params[:item_id].to_i
    item = params[:item]
    case type
    when '0'
      option = Option.create_by_option_name(:project_types)
      opt_val = option.option_value.split(",")
      opt_val[item_number] = item
      option.update_attribute(:option_value, opt_val.join(","))
    when '1'
      option = Option.create_by_option_name(:moneitions)
      opt_val = option.option_value.split(",")
      opt_val[item_number] = item
      option.update_attribute(:option_value, opt_val.join(","))
    when '2'
      option = Option.create_by_option_name(:expense_items)
      opt_val = option.option_value.split(",")
      opt_val[item_number] = item
      option.update_attribute(:option_value, opt_val.join(","))
    when '3'
      option = Option.create_by_option_name(:expense_payments)
      opt_val = option.option_value.split(",")
      opt_val[item_number] = item
      option.update_attribute(:option_value, opt_val.join(","))
    end
    redirect_to action: :setting
  end

  def delete_items
    type = params[:object]
    item_number = params[:id].to_i

    case type
    when '0'
      option = Option.create_by_option_name(:project_types)
      opt_val = option.option_value.split(",")
      opt_val.delete_at(item_number)
      option.update_attribute(:option_value, opt_val.join(","))
    when '1'
      option = Option.create_by_option_name(:moneitions)
      opt_val = option.option_value.split(",")
      opt_val.delete_at(item_number)
      option.update_attribute(:option_value, opt_val.join(","))
    when '2'
      option = Option.create_by_option_name(:expense_items)
      opt_val = option.option_value.split(",")
      opt_val.delete_at(item_number)
      option.update_attribute(:option_value, opt_val.join(","))
    when '3'
      option = Option.create_by_option_name(:expense_payments)
      opt_val = option.option_value.split(",")
      opt_val.delete_at(item_number)
      option.update_attribute(:option_value, opt_val.join(","))
    end
    redirect_to action: :setting
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    token = params[:stripeToken]    
    @user = User.new(params[:user].permit(:first_name, :last_name, :email, :password, :password_confirmation))
    
    if params[:member].present? and User::MEMBER_TYPES.include?(params[:member])
      @user.member_type = User::MEMBER_TYPES.index(params[:member])
    else
      @user.member_type = 0
    end

    if token.nil?
      respond_to do |format|
        format.html { render action: :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        flash[:error] = "Oh snap! Please check your card number"        
      end
    else
      begin
        coupon = Stripe::Coupon.create(
          :percent_off => 100,
          :duration => 'repeating',
          :duration_in_months => 1,
          :id => @user.id
        )
        
        if params[:member] == User::MEMBER_TYPES[0]
          customer = Stripe::Customer.create(
            :card => token,
            :plan => User::MEMBER_TYPES[@user.member_type],
            :email => @user.email,
            :coupon => coupon,
            :description=> @user.name
          )
        else
          customer = Stripe::Customer.create(
            :card => token,
            :plan => User::MEMBER_TYPES[@user.member_type],
            :email => @user.email,
            :description=> @user.name
          )
        end      

        @user.customer_id = customer.id
        @user.status = 'live'
        if @user.save
          p_profile = @user.build_payment_profile(exp_month: params[:exp_month], exp_year: params[:exp_year], ccard_last4: params[:cvc_number])
          p_profile.save
          @user.owners.create(name:@user.name, email:@user.email)
          sign_in(:user, @user)
          super
          redirect_to user_thanks_path and return
        else
          customer.delete
          respond_to do |format|
            format.html { render action: :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      rescue Stripe::CardError => e
        respond_to do |format|
          format.html { render action: :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
          flash[:error] = "Oh snap! Your payment failed please try again or contact your bank"
        end
      end
    end
  end

  def update
    super
  end

  protected

  def after_sign_up_path_for(resource)
    new_user_session_path
  end

  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    user = User.where(email:params[:user][:email]).first
    if user.present? and !user.is_admin? and user.payment_profile.nil?
      flash[:notice] = "Please select package"
      redirect_to user_pricing_path(user.id) and return
    elsif user.present? and user.status == 'expired'
      flash[:notice] = "Your account was expired, please contact to admin "
      redirect_to  home_contact_path  and return
    else
      super
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController    
  before_filter :authenticate_user!, except: [:pricing, :purchase] #, :only => [:setting, :update, ]
  skip_before_filter :verify_authenticity_token, :only => [:add_card, :purchase]
  @@process = -1  
  def index    
    #@users = User.all
  end

  def update
    user = current_user
    data = ''
    case params[:state]
    when '0'
      if user.update_attributes(first_name:params[:user][:first_name], last_name:params[:user][:last_name], email:params[:user][:email])
        data = {:success => 'Updated your basic information successfully'}
      else
        data = {:failure => user.errors.messages}
      end
    when '1'
      if user.valid_password?(params[:user][:cur_password])
        if user.update_attributes(password:params[:user][:password], password_confirmation:params[:user][:password_confirmation])
          data = {:success => 'Changed your password'}
        else
          data = {:failure => user.errors.messages}
        end
      else
        data = {:failure => "Please check your current password"}
      end
    when '2'
      st_dt = params[:user][:start_financial_year].present? ? Date.strptime(params[:user][:start_financial_year], "%d/%m/%Y") : nil
      ed_dt = params[:user][:end_financial_year].present? ? Date.strptime(params[:user][:end_financial_year], "%d/%m/%Y") : nil
      
      if user.update_attributes(start_financial_year:st_dt, end_financial_year:ed_dt, default_currency:params[:user][:default_currency], income_target:params[:user][:income_target], year_budget:params[:user][:year_budget], send_me_alert:params[:user][:send_me_alert])
        data = {:success => 'Updated your other informations successfully'}
      else
        data = {:failure => user.errors.messages}
      end
    end
    render json:data and return
  end

  def setting
    @user = current_user
    @uploaded_file = current_user.uploaded_file_size
    @upload_state = (@uploaded_file/current_user.file_limit)*100    
  end

  def add_card    
    user = current_user    
    token = params[:stripeToken]
    if token.present?
      if user.payment_profile.present?
        p_profile = user.payment_profile
        p_profile.update_attributes(first_name: params[:card_user_name], exp_month: params[:exp_month], exp_year: params[:exp_year], ccard_last4: params[:cvc_number])
      else        
        p_profile = user.build_payment_profile(first_name: params[:card_user_name], exp_month: params[:exp_month], exp_year: params[:exp_year], ccard_last4: params[:cvc_number])
        p_profile.save
        customer = Stripe::Customer.create(
          :card => token,
          :plan => "large",
          :email => user.email,
          :description=> user.name
        )
      end
    end
    user.update_attributes(customer_id:customer.id)
    redirect_to action: :setting
  end

  def destroy
    @user = current_user
    @user.destroy
    
    cu = Stripe::Customer.retrieve(@user.customer_id)
    cu.delete
    sign_out
    flash[:notice] = "We're sorry to see you go."
    #flash[:notice] = "We're sorry to see you go. Send us some feedback before you go!"    
    redirect_to root_path    
  end


  def pricing
    @user = User.find(params[:id])
    @member_price = @user.member_price
    #User::MEMBER_TYPES[@user.member_type]
  end

  def purchase
    @user = User.find(params[:user_id])
    token = params[:stripeToken]
    begin
      customer = Stripe::Customer.create(
        :card => token,
        :plan => User::MEMBER_TYPES[@user.member_type],
        :email => @user.email,
        :description=> @user.name
      )
      @user.update_attributes(customer_id:customer.id)

      if @user.payment_profile.present?
        p_profile = @user.payment_profile
        p_profile.update_attributes(exp_month: params[:exp_month], exp_year: params[:exp_year], ccard_last4: params[:cvc_number])        
      else
        p_profile = @user.build_payment_profile(exp_month: params[:exp_month], exp_year: params[:exp_year], ccard_last4: params[:cvc_number])
        p_profile.save
      end

      sign_in(:user, @user)
      redirect_to user_thanks_path and return

    rescue Stripe::CardError => e
      redirect_to user_pricing_path(@user.id)
      flash[:error] = "Oh snap! Your payment failed please try again or contact your baknk"
    end
    # customer = Stripe::Customer.create(
    #   :card => token,
    #   :plan => "large",
    #   :email => @user.email
    # )
  end

  def thanks    
  end

  def money_converting
    @@process += 1
    render json: {success: @@process}
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.row.future-projects  
  .row
    .col-md-6
      %h1.form-title Users
    .col-md-4
      
    .col-md-1
      /= link_to "New Project", new_project_path, class: 'btn btn-primary', style: "margin-top: 32px;", :"data-no-turbolink"=>true
  .col-md-10
    .row
      %table.table.table-hover.table-condensed.table-bordered.table-striped.project-list
        %thead
          %tr
            %th{style:'width: 30%'} Name
            %th{style:'width: 5%'} Code
            %th{style:'width: 10%'} Type
            %th{style:'width: 10%'} Monistation
            %th{style:'width: 5%'} Total Budget
            %th{style:'width: 5%'} DueDate
            %th{style:'width: 5%'} Mange
        %tbody
          - @projects.each do |p|
            %tr
              %td
                = link_to p.name, project_path(p)
              %td= p.site_code
              %td= p.type_name
              %td= p.monetisation_name
              %td= p.budget
              %td= p.end_date.strftime("%d/%m/%Y") if p.end_date.present?
              %td
                = link_to(make_live_path(p), class: 'btn-mini', title:'Make Project Live') do
                  %i.glyphicon.glyphicon-exclamation-sign
                = link_to(edit_project_path(p), class: 'btn-mini', title:'Edit', :"data-no-turbolink"=>true) do
                  %i.glyphicon.glyphicon-pencil
                = link_to(project_path(p), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}, title:'Delete') do
                  %i.glyphicon.glyphicon-trash
                

        %tfoot
          %tr
            %td.digg_pagination{colspan:6}
              = will_paginate @projects, previous_label: '< PREV', next_label: 'NEXT >' if @projects.present?
  .col-md-2
    %label 
      = DateTime.now.year
      Budget Available for this year of budget Allocated

app/views/users/setting.html.haml
= form_for @user, url: user_update_path, remote: true, html:{class: "form-horizontal basic-info-form user-setting-form"} do |f|
  .row
    .col-xs-6.col-sm-6.col-md-6
      .block
        %h4 Basic Info
        .line
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 First Name
          .col-xs-4.col-sm-4.col-md-4
            = f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name", class: 'form-control'
        .blank
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 Last Name
          .col-xs-4.col-sm-4.col-md-4
            = f.text_field :last_name, placeholder: "Last Name", class: 'form-control'
        .blank
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 E-mail Address
          .col-xs-4.col-sm-4.col-md-4
            = f.text_field :email, required: true, placeholder: "xxx@xxx.com", class: 'form-control'
        .blank
        .row
          .col-xs-3.col-sm-3.col-md-3
          .col-xs-4.col-sm-4.col-md-4
            %button#basic_info_save_btn.btn.btn-default{type: "submit"} Save
        = hidden_field_tag :state, '0'
/ = form_for @user, url: user_update_path, html:{class: "form-horizontal user-invite-form"} do |f|
/   .row
/     .col-xs-6.col-sm-6.col-md-6
/       .block
/         %h3 Friends Who Can Access My Stuff
/         .line
/         .row
/           .col-xs-6.col-sm-6.col-md-6
/             .table-responsive
/               %table.table.table-striped
/                 %tbody
/                   %tr
/                     %td mike@example.com
/                     %td
/                       %a{href: "#"} remove
/                   %tr
/                     %td terri@example.com
/                     %td
/                       %a{href: "#"} remove
/                   %tr
/                     %td short774@hotmail.com
/                     %td
/                       %a{href: "#"} remove
/         .row
/           .col-xs-3.col-sm-3.col-md-3
/             %h5 Invite a person:
/           .col-xs-3.col-sm-3.col-md-3
/             %input.form-control{placeholder: "msmith@whatever.com", type: "text"}/
/           .col-xs-3.col-sm-3.col-md-3
/             %button.btn.btn-default{type: "submit"} Invite
= form_for @user, url: user_update_path, remote: true, html:{class: "form-horizontal change-password-form user-setting-form"} do |f|
  .row
    .col-xs-6.col-sm-6.col-md-6
      .block
        %h4 Change My Password
        .line
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 Current Password
          .col-xs-4.col-sm-4.col-md-4
            = f.password_field :cur_password, required: true, placeholder: "********", class: 'form-control'
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 New Password
          .col-xs-4.col-sm-4.col-md-4
            = f.password_field :password, required: true, placeholder: "********", class: 'form-control'
        .blank
        .row
          .col-xs-3.col-sm-3.col-md-3
            %h5 Re-type Password
          .col-xs-4.col-sm-4.col-md-4
            = f.password_field :password_confirmation, required: true, placeholder: "********", class: 'form-control'
        .blank
        .row
          .col-xs-3.col-sm-3.col-md-3
          .col-xs-4.col-sm-4.col-md-4
            %button.btn.btn-default{type: "submit"} Change
        = hidden_field_tag :state, '1'
= form_for @user, url: user_update_path, remote: true, html:{class: "form-horizontal account-change-form user-setting-form"} do |f|
  .row
    .col-xs-6.col-sm-6.col-md-6
      .block
        %h4 My Account
        .line
        %div MyWebApp Plus.  $49 per month.  Up to 5 Super Cool Thingies.
        %div Unlimited This, Unlimited That, Unlimited The Other.
        %div          
          = link_to "Close Your Account", users_destroy_path, data:{confirm:"Are you sure?"}, method: :delete

.row
  .col-xs-6.col-sm-6.col-md-6
    .block
      %h4 Credit Card
      .line
      %form.form-horizontal{role: "form"}
        .form-group
          %label.col-xs-4.col-sm-4.col-md-4 Type
          .col-xs-8.col-sm-8.col-md-8
            = image_tag "card_type.png"
        .form-group
          %label.col-xs-4.col-sm-4.col-md-4 Name on Card
          .col-xs-8.col-sm-8.col-md-8= @user.payment_profile.present? ? @user.payment_profile.first_name : ''
        .form-group
          %label.col-xs-4.col-sm-4.col-md-4 Credit Card Number
          .col-xs-8.col-sm-8.col-md-8 
            ************
            = @user.payment_profile.present? ? @user.payment_profile.ccard_last4 : ''
        .form-group
          %label.col-xs-4.col-sm-4.col-md-4 Expiration Date
          .col-xs-8.col-sm-8.col-md-8 
            = @user.payment_profile.present? ? @user.payment_profile.exp_month : ''
            %span /
            = @user.payment_profile.present? ? @user.payment_profile.exp_year : ''
        .form-group
          .col-xs-2.col-xs-offset-4
            = link_to "Edit", "#", class:"btn btn-default col-xs-12", :"data-toggle"=>"modal", :"data-target"=>"#modal_credit_card"
          
= form_for @user, url: user_update_path, remote: true, html:{class: "form-horizontal other-setting-form user-setting-form"} do |f|
  .row
    .col-xs-6.col-sm-6.col-md-6
      .block
        %h4 Other Settings
        .line
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 Start of Financial Year
          .col-xs-4.col-sm-4.col-md-4
            #start.input-group.date
              = f.text_field :start_financial_year, value:f.object.start_financial_year.present? ? f.object.start_financial_year.strftime("%d/%m/%Y") : "", class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        .blank
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 End of Financial Year
          .col-xs-4.col-sm-4.col-md-4
            #stop.input-group.date
              = f.text_field :end_financial_year, value: f.object.end_financial_year.present? ? f.object.end_financial_year.strftime("%d/%m/%Y") : "", class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        .blank
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 Default Currency
          .col-xs-4.col-sm-4.col-md-4
            - if f.object.default_currency.present?
              = Payment::CURRENCY_TYPES[f.object.default_currency]
              = f.hidden_field :default_currency
            - else              
              = f.select :default_currency, options_for_select(Payment::CURRENCY_TYPES.map{|ct| [ct, Payment::CURRENCY_TYPES.index(ct)]}, f.object.default_currency.present? ? f.object.default_currency : '' ), {include_blank: true}, {class: 'form-control'}
            
        .blank
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 Yearly Income Target
          .col-xs-4.col-sm-4.col-md-4
            = f.text_field :income_target, placeholder: "", class: 'form-control'
        .blank
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 
              ="#{Time.now.year} Budget"
          .col-xs-4.col-sm-4.col-md-4
            = f.text_field :year_budget, placeholder: "", class: 'form-control'
        .blank
        .row
          .col-xs-4.col-sm-4.col-md-4
            %h5 Send me alerts
          .col-xs-4.col-sm-4.col-md-4
            = f.select :send_me_alert, options_for_select(User::SEND_ME_ALERT_TYPES.map{|at| [at, User::SEND_ME_ALERT_TYPES.index(at)]}, f.object.send_me_alert.present? ? f.object.send_me_alert : ''), {include_blank: true}, {class: 'form-control'}
        = hidden_field_tag :state, '2'
        .row
          .col-xs-3.col-sm-3.col-md-3.col-sm-offset-1          
            %button.btn.btn-default{type: "button", :onclick=>'$(".other-setting-form").submit();'} Update
.row
  .col-md-6
    .block
      %h5 
        = "File Upload Limit is#{current_user.file_limit}Mb and You have used #{@uploaded_file}Mb"
      .line
      = progress_bar(@upload_state, :color => 'blue', :rounded => true, class: 'test-progress')

#modal_credit_card.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Add Credit Card
      .modal-body.form-horizontal
        = form_tag(users_add_card_path, remote: true, id:'checkout_form', class:'form-horizontal') do |f|
          = javascript_include_tag "https://js.stripe.com/v2/"
          .container{style:'width:100%;'}
            %span.payment-errors{style:'color: red;font-weight: 600;'}
            .col-sm-12
              %fieldset
                .control-group
                  %label.control-label{"label-default" => ""} Card Holder's Name
                  .controls
                    %input.form-control{pattern: "\\w+ \\w+.*", required: "", title: "First and last name", type: "text", name: "card_user_name"}/
                .control-group
                  %label.control-label{"label-default" => ""} Card Number
                  .controls
                    .row
                      .col-md-3
                        %input.card-numbers.form-control{autocomplete: "off", maxlength: "4", pattern: "\\d{4}", required: "", title: "First four digits", type: "text"}/
                      .col-md-3
                        %input.card-numbers.form-control{autocomplete: "off", maxlength: "4", pattern: "\\d{4}", required: "", title: "Second four digits", type: "text"}/
                      .col-md-3
                        %input.card-numbers.form-control{autocomplete: "off", maxlength: "4", pattern: "\\d{4}", required: "", title: "Third four digits", type: "text"}/
                      .col-md-3
                        %input.card-numbers.form-control{autocomplete: "off", maxlength: "4", pattern: "\\d{4}", required: "", title: "Fourth four digits", type: "text"}/
                    %input#card_number{:type=>"hidden", :"data-stripe"=>"number"}
                .control-group
                  %label.control-label{"label-default" => ""} Card Expiry Date
                  .controls
                    .row
                      .col-md-9
                        %select.form-control{name: "exp_month", :"data-stripe" => "exp-month"}
                          %option{value: "01"} January
                          %option{value: "02"} February
                          %option{value: "03"} March
                          %option{value: "04"} April
                          %option{value: "05"} May
                          %option{value: "06"} June
                          %option{value: "07"} July
                          %option{value: "08"} August
                          %option{value: "09"} September
                          %option{value: "10"} October
                          %option{value: "11"} November
                          %option{value: "12"} December
                      .col-md-3
                        = select_year(Date.today, {start_year: Date.today.year-3, end_year: Date.today.year+8}, {class:'form-control', :"data-stripe" => "exp-year", name: "exp_year"})
                .control-group
                  %label.control-label{"label-default" => ""} Card CVV
                  .controls
                    .row
                      .col-md-3
                        %input.form-control{autocomplete: "off", maxlength: "4", pattern: "\\d{4}", required: "", title: "Three digits at back of your card", type: "text", :"data-stripe" => "cvc", name:'cvc_number'}/
                      .col-md-8
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        %button#update_card.btn.btn-primary.update{type: "button"} Update

:css
  .bar_container{
    border-radius: 5px;
    padding: 5px 0;
  }
  .bar_container .bar_mortice{
    margin-top: -5px;
  }
  .bar_container .bar_mortice .progress{
    text-align: center;
  }

:javascript
  $(".card-numbers").change(function(){
    card_num = $(".card-numbers").eq(0).val() + $(".card-numbers").eq(1).val() + $(".card-numbers").eq(2).val() + $(".card-numbers").eq(3).val()
    $("#card_number").val(card_num)
  });
  
  $("#update_card").click(function(){
    $("#checkout_form").submit();
  });

  $(".user-setting-form").on('ajax:success',function(event, data, status, xhr){
    if(data.success){
      alert(data.success);
    }else{
      alert(data.failure);
    }
  });

app/views/users/setting_tmp.html.haml
  / var progresspump = setInterval(function(){
  /   $.get("/user/money_converting", function(data){
  /     data = data.success;
  /     $(".progress").css('width',data+'%');
  /     $(".progress").html(data+'%');
  /     if(data > 99.999) {
  /       clearInterval(progresspump);
  /       $(".progressouter").removeClass("active");
  /       $(".progress").html("Done");
  /     }
  /   })
  / }, 500);

app/views/users/thanks.html.haml
.row
  .col-md-offset-2.col-md-8
    %h1.form-title Thank you for joining
    %h3.form-title Please check your email for the confirmatin email