config/routes.rb
Bluadmin::Application.routes.draw do  
  captcha_route
  mount StripeEvent::Engine => '/stripe'
  
  namespace :admin do
    resources :users, only: [:index]
    get "send_to_reset_password_email/:id" => "users#send_to_reset_password_email", as: 'send_to_reset_password_email'
    get "setting"             => "users#setting"
    post "new_item"           => "users#new_item"
    match "update_option"     => 'users#update_setting_option',        via: [:post, :patch]
    delete "delete_items/:id"     => "users#delete_items", as: "delete_items"
    
  end
  
  get 'home/index'
  get 'home/about'
  match 'home/contact'             => 'home#contact',        via: [:get, :post]
  get 'home/features'
  get 'home/pricing'

  resources :expenses
  resources :payment_profiles
  resources :projects  
  get 'projects/make_live/:id'                  => 'projects#make_live',   as: 'make_live'

  resources :individual_projects
  get "get_year_data"                           => 'individual_projects#get_year_data'
  get "get_year_bulk_data"                      => 'individual_projects#get_year_bulk_data'

  resources :accounts
  resources :articles
  resources :keywords 
  resources :tasks

  resources :attach_files, only:[:create, :destroy]

  post 'tasks/mark_as_complete/:id'             => 'tasks#mark_as_complete', as: 'mark_as_complete'
  post 'tasks/mark_as_uncomplete/:id'           => 'tasks#mark_as_uncomplete', as: 'mark_as_uncomplete'
  post 'add_new_owner'                          => 'tasks#add_new_owner', as: 'add_new_owner'

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }

  get 'users/index'
  get 'users/setting'

  post 'users/add_card'
  delete 'users/destroy'          => 'users#destroy'
  match 'user/update'             => 'users#update',        via: [:post, :patch]
  
  get 'user/pricing/:id'          => 'users#pricing',       as: 'user_pricing'
  post 'user/purchase'            => 'users#purchase'
  get 'user/thanks'               => 'users#thanks'
  get 'user/money_converting'     => 'users#money_converting'

  post '/tinymce_assets' => 'projects#upload_image'
  
  post '/home/set_option'         => 'home#set_option'

  resources :init_projects
  post '/projects/import_csv'     => 'init_projects#import_csv'
  
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, only: [:set_option]
  def index    
    if current_user.present?
      @projects = current_user.live_projects.live_projects.paginate(page: params[:page], :per_page => 10)
      step = 0
      profits = []
      if Option.option_value(current_user, :all_site_profit)
        @chart1 = LazyHighCharts::HighChart.new('basic_line') do |f|
          f.title(:text => "All Projects")
          f.xAxis(:categories => Date::MONTHNAMES.reject{|m| m.nil?}.map{|m| m[0..2]})
          if current_user.live_projects.count > 0
            current_user.live_projects.each do |project|
              if project.have_figure?
                values = []
                [*1..12].each do |m|
                  values[m-1] = project.profit_loss_by_month(Time.now.year, m)
                end
                profits << values
                f.series(:name => project.site_code, :yAxis => 0, :data => profits[step])
                step += 1
              end
              # break if step == 12
            end
          else
            f.series(:name => ['none'], :yAxis => 0, :data => [0])
          end
          f.legend(:align => 'right', :verticalAlign => 'top', :y => 40, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'line', marginRight: 15, marginLeft: 50,marginBottom: 30, marginTop: 60, :defaultSeriesType=>"column" })
        end
      end

      income_values = []
      target_values = []
      if Option.option_value(current_user, :top_earning)
        [*1..12].each do |m|
          income = current_user.monthly_incomes.incomes_of_month(Time.now.year, m)
          target = current_user.live_projects.target_of_month(Time.now.year, m)
          income_values[m-1] = income
          target_values[m-1] = target
        end
        @chart2 = LazyHighCharts::HighChart.new('basic_line') do |f|
          f.title(:text => "Top Earning")
          f.xAxis(:categories =>  Date::MONTHNAMES.reject{|m| m.nil?}.map{|m| m[0..2]})
          f.series(:name => "Income", :yAxis => 0, :data => income_values)
          f.series(:name => "Target", :yAxis => 0, :data => target_values)
          f.legend(:align => 'right', :verticalAlign => 'top', :y => 0, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'line', marginRight: 15, marginLeft: 50,marginBottom: 30, marginTop: 60, :defaultSeriesType=>"column" })
        end
      end

      income_values = []
      expense_values = []
      if Option.option_value(current_user, :all_site_expenses)
        [*1..12].each do |m|
          income = current_user.monthly_incomes.incomes_of_month(Time.now.year,m)
          expense = current_user.expenses.amount_of_month(Time.now.year, m)
          income_values[m-1] = income
          expense_values[m-1] = expense
        end
        @chart3 = LazyHighCharts::HighChart.new('basic_line') do |f|
          f.title(:text => "Expenses V Earnings")
          f.xAxis(:categories =>  Date::MONTHNAMES.reject{|m| m.nil?}.map{|m| m[0..2]})
          f.series(:name => "Expenses", :yAxis => 0, :data => expense_values)
          f.series(:name => "Income", :yAxis => 0, :data => income_values)

          f.legend(:align => 'right', :verticalAlign => 'top', :y => 0, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'line', marginRight: 15, marginLeft: 50,marginBottom: 30, marginTop: 60, :defaultSeriesType=>"column" })
        end
      end

      if Option.option_value(current_user, :monthly_income_monthly_target)
        m_incomes = current_user.monthly_incomes.incomes_of_month(Time.now.year, Time.now.month)
        m_targets = current_user.live_projects.target_of_month(Time.now.year, Time.now.month)
        @chart4 = LazyHighCharts::HighChart.new('column') do |f|
          f.title(:text => "MonthlyIncome VS MonthlyTarge")
          f.xAxis(:categories => ['Monthly Income', 'Monthly Target'])
          f.series(:name => "Value", :yAxis => 0, :data => [m_incomes, m_targets])

          f.legend(:align => 'right', :verticalAlign => 'top', :y => -10, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'column', marginRight: 15, marginLeft: 50,marginBottom: 30, :defaultSeriesType=>"column" })
        end
      end

      if Option.option_value(current_user, :last_year_current_year)
        lst_profit = current_user.live_projects.profit_loss_by_year(Time.now.year.to_i - 1)
        cur_profit = current_user.live_projects.profit_loss_by_year(Time.now.year.to_i)
        @chart5 = LazyHighCharts::HighChart.new('column') do |f|
          f.title(:text => "#{Time.now.year.to_i - 1} Profit/Loss VS #{Time.now.year} Profit/Loss")
          f.xAxis(:categories => ["#{Time.now.year.to_i - 1 }", "#{Time.now.year}"])
          f.series(:name => "Profit/Loss", :yAxis => 0, :data => [lst_profit, cur_profit] )

          f.legend(:align => 'right', :verticalAlign => 'top', :y => -10, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'column', marginRight: 15, marginLeft: 50,marginBottom: 30, :defaultSeriesType=>"column" })
        end
      end

      if Option.option_value(current_user, :top_expenses)
        
        items = current_user.expenses.all.map(&:item_type).uniq
        values = []
        item_value = items.count == 0 ? [0] : []
        item_label = items.count == 0 ? ['none'] : []
        
        items.each do |item|
          exp = current_user.expenses.where(item_type:item)
          if exp.count > 0
            values << [exp.map{|ex| ex.amount}.sum, Expense.item_types[item.to_i]]
          end
        end
        
        if values.count > 0
          values = values.sort{|x, y| y <=> x}
          values[0..4].each do |value|
            item_value << value[0]
            item_label << value[1]
          end
        end

        lst_profit = current_user.live_projects.profit_loss_by_year(Time.now.year.to_i - 1)
        cur_profit = current_user.live_projects.profit_loss_by_year(Time.now.year.to_i)
        @chart6 = LazyHighCharts::HighChart.new('column') do |f|
          f.title(:text => "Top Expenses")
          f.xAxis(:categories => item_label)
          f.series(:name => "Expense", :yAxis => 0, :data => item_value)

          f.legend(:align => 'right', :verticalAlign => 'top', :y => -10, :x => 10, :layout => 'vertical', width: 0,)
          f.chart({type: 'column', marginRight: 15, marginLeft: 45,marginBottom: 30, :defaultSeriesType=>"column" })
        end
      end
    end
  end

  def about
  end

  def contact
    if request.post?
      if valid_captcha?(params[:captcha])
        UserMailer.contact_email(params[:name], params[:email], params[:text]).deliver
        flash[:notice] = "Sent email successfully"
        redirect_to home_contact_path
      else
        flash[:error] = "Please check capcha again"
        redirect_to home_contact_path
      end
    end
  end

  def pricing
  end

  def features
  end

  def set_option
    option_list = %w[all_site_profit top_earning all_site_expenses monthly_income_monthly_target last_year_current_year top_expenses]
    if params[:rest_to_default] == "1"      
      option_list.each do |key, value|
        opt = current_user.options.where(option_name:key).first
        opt.update_attribute(:option_value, false) if opt.present?
      end
      option_list[0..2].each do |key, value|
        opt = current_user.options.where(option_name:key).first
        opt.update_attribute(:option_value, true) if opt.present?
      end
    else
      params[:h_option].each do |key, value|
        option = current_user.options.where(option_name:key).first
        if option.present?
          option.update_attribute(:option_value, value)
        else
          current_user.options.create(option_name:key,option_value:value)
        end
      end
    end    
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/about.html.haml
%br/
%br/
%br/
%br/
.row
  .col-md-4
    %label Lorem ipsum dolor sit amet, cum cuiisque adipisci reprimique, nominavi percipitur has ne. Duis mangna pericula ut usu. Eu dicant Vulputate comprehensam eum, ius cibo
    %br/
    %br/
    %label Lorem ipsum dolor sit amet, cum cuiisque adipisci reprimique, nominavi percipitur has ne. Duis mangna pericula ut usu. Eu dicant Vulputate comprehensam eum, ius cibo
    %br/
    %br/
    %label Lorem ipsum dolor sit amet, cum cuiisque adipisci reprimique, nominavi percipitur has ne. Duis mangna pericula ut usu. Eu dicant Vulputate comprehensam eum, ius cibo
    %br/
    %br/
    %label Lorem ipsum dolor sit amet, cum cuiisque adipisci reprimique, nominavi percipitur has ne. Duis mangna pericula ut usu. Eu dicant Vulputate comprehensam eum, ius cibo
  .col-md-8
    .about-img-box{style:'border: solid 3px #ddd;background-color: #eee;border-radius: 10px;'}
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      %br/
      

app/views/home/contact.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1.form-title Contact US
    .row
      = form_for :contact, url: home_contact_path, html:{class: "form-horizontal"} do |f|
        .form-group
          .col-sm-8.col-sm-offset-2            
            = text_field_tag :name, nil, required: true, placeholder: 'Name', class: 'form-control'
        .form-group
          .col-sm-8.col-sm-offset-2            
            = email_field_tag :email, nil, required: true, placeholder: 'Email', class: 'form-control'
        .form-group
          .col-sm-8.col-sm-offset-2
            = captcha_tag
        .form-group
          .col-sm-8.col-sm-offset-2            
            = text_field_tag :captcha
        .form-group
          .col-sm-8.col-sm-offset-2            
            = text_area_tag :text, nil, required: true, class: "form-control"
        
        .form-group
          .col-sm-offset-2.col-sm-10
            %button.btn.btn-default{type: "submit"} Send


:css
  .contact{background-color: #444;}

app/views/home/features.html.haml
.row
  .col-md-9
    .row
      .panel.hello-panel
        %h4 The Most Amazing Web App You've Ever Seen
        %label Lerem ipsum dolor sit amet, consectetr adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolare magna aliqua. Ut enim ad minim veniam, quis nostrud exerctation ullamco laoris nisi ut aliquip ex ea commodo consequat.
    .row
      .row
        .col-md-6
          .panel.hello-panel{style:'height: 142px;'}
            %h4 Consectetur Adipisicing Elit
            %label Excepteur sint sccaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            %br/
            %br/
            %br/
            %br/
            %br/
            %br/
        .col-md-6
          .panel.hello-panel
            %br/
            %br/
            %br/
            %br/
            %br/
      .row
        .col-md-6
          .panel.hello-panel{style:'height: 142px;'}
            %label Ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate belit esse cillum dolore.
            %br/
            %br/
            %br/
            %br/
            %br/
            %br/
        .col-md-6
          .panel.hello-panel
            %br/
            %br/
            %br/
            %br/
            %br/
      .row
        .col-md-6
          .panel.hello-panel{style:'height: 142px;'}
            %label Ea commodo consequat. Duis aute irure dolor in reprehenderit in valuptate velit esse cillum dolore.
            %br/
            %br/
            %br/
        .col-md-6
          .panel.hello-panel
            %br/
            %br/
            %br/
            %br/
            %br/
    .row
      .col-md-offset-6.col-md-3
        %label 
          See the 
          = link_to "FAQ", "#"
          or 
          = link_to "Sign up now", new_user_session_path
  %br/
  %br/
  %br/
  %br/
  %br/
  .col-md-3
    .row
      = link_to "Sign up Now", new_registration_path(resource_name), class: 'btn btn-danger col-md-12', :"data-no-turbolink"=>true
    %br/
    %br/    
    .row
      .sign-up-now-box{style:"border: 2px solid #ddd;border-radius: 10px;height: 200px;width: 100%;"}

app/views/home/index.html.haml
.row
  - if current_user.present?
    .row
      .row
        .col-md-12
          .row
            - if Option.option_value(current_user, :all_site_profit)
              #chart1.col-md-4
              = high_chart("chart1", @chart1)
            - if Option.option_value(current_user, :top_earning)
              #chart2.col-md-4
              = high_chart("chart2", @chart2)
            - if Option.option_value(current_user, :all_site_expenses)
              #chart3.col-md-4
              = high_chart("chart3", @chart3)
            - if Option.option_value(current_user, :monthly_income_monthly_target)
              #chart4.col-md-4
              = high_chart("chart4", @chart4)
            - if Option.option_value(current_user, :last_year_current_year)
              #chart5.col-md-4
              = high_chart("chart5", @chart5)
            - if Option.option_value(current_user, :top_expenses)
              #chart6.col-md-4
              = high_chart("chart6", @chart6)
          .blank
          .row
            .col-xs-4.col-sm-4.col-md-4              
              = link_to "Edit Dashboard Charts", "#", class:"btn btn-default", :"data-toggle" => "modal", :"data-target" => "#modal_edit_dashboard_charts"
            .col-xs-8.col-sm-8.col-md-8
              %h3 Project Summary
        
      .blank
      .row
        .col-md-8
          .table-responsive
            %table.table.table-striped.table-bordered.table-hover
              %thead
                %tr
                  %th{style:'width: 40%'} Name
                  %th{style:'width: 5%'} SiteCode
                  %th{style:'width: 5%'} Profit/Loss
                  %th{style:'width: 5%'} Monthly Avg
                  %th{style:'width: 5%'} Monthly Target
                  /%th{style:'width: 5%'} Prjctd
                  %th{style:'width: 5%'} Total Budget
                  %th{style:'width: 5%'} Mange
              %tbody
                - @projects.each do |p|
                  - if p.profit_loss > 0 
                    %tr
                      %td{style:'background-color: green;color: white;'}= link_to p.name, project_path(p), style:'color: white;'
                      %td{style:'background-color: green;color: white;'}= p.site_code
                      %td{style:'background-color: green;color: white;'}
                        = "#{current_user.currency_symbol}#{p.profit_loss}"
                      %td{style:'background-color: green;color: white;'}
                        = "#{current_user.currency_symbol}#{(p.yearly_income(Time.now.year) / 12).round(2)}"
                      %td{style:'background-color: green;color: white;'}
                        = "#{current_user.currency_symbol}#{p.monthly_target}"
                      %td{style:'background-color: green;color: white;'}
                        = "#{current_user.currency_symbol}#{p.budget}"
                      %td
                        = link_to(edit_individual_project_path(p), class: 'btn-mini') do
                          %i.glyphicon.glyphicon-pencil
                        = link_to(individual_project_path(p), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                          %i.glyphicon.glyphicon-trash
                  - else
                    %tr
                      %td{style:'background-color: red;color: white;'}= link_to p.name, project_path(p), style:'color: white;'
                      %td{style:'background-color: red;color: white;'}= p.site_code
                      %td{style:'background-color: red;color: white;'}= p.profit_loss
                      %td{style:'background-color: red;color: white;'}= (p.yearly_income(Time.now.year) / 12).round(2)
                      %td{style:'background-color: red;color: white;'}= p.monthly_target
                      %td{style:'background-color: red;color: white;'}= p.budget
                      %td
                        = link_to(edit_individual_project_path(p), class: 'btn-mini') do
                          %i.glyphicon.glyphicon-pencil
                        = link_to(individual_project_path(p), class: 'btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                          %i.glyphicon.glyphicon-trash
              %tfoot
                %tr
                  %td.digg_pagination{colspan:7}
                    = will_paginate @projects, previous_label: '< PREV', next_label: 'NEXT >' if @projects.present?
        .col-md-4
          .table-responsive
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th Name
                  %th Figure
              %tbody
                %tr
                  %td 
                    = Time.now.year
                    Budget
                  %td= "#{current_user.currency_symbol} #{current_user.year_budget}"
                %tr
                  %td Overall Spend
                  %td= "#{current_user.currency_symbol} #{current_user.expenses.amount_of_all.round(2)}"
                %tr
                  %td Profit
                  %td= "#{current_user.currency_symbol} #{current_user.projects.profit_loss_by_year Time.now.year}"
                %tr
                  %td This Months Expenses
                  %td= "#{current_user.currency_symbol} #{current_user.expenses.amount_of_month(Time.now.year, Time.now.month)}"
                %tr
                  %td This Month Profit
                  %td= "#{current_user.currency_symbol} #{ current_user.monthly_incomes.incomes_of_month(Time.now.year, Time.now.month) - current_user.expenses.amount_of_month(Time.now.year, Time.now.month)}"
                %tr
                  %td Overall Monthly Income Target
                  %td= "#{current_user.currency_symbol} #{current_user.monthly_incomes.incomes_of_month(Time.now.year, Time.now.month)}"
                %tr
                  %td Yearly Income Target
                  %td= "#{current_user.currency_symbol} #{current_user.income_target}"
                %tr
                  %td
                    = Time.now.year 
                    Income So Far
                  %td= "#{current_user.currency_symbol} #{current_user.monthly_incomes_sum}"

  - else
    .row
      .col-md-9{style:'background-color: #ddd;border-radius: 10px;padding: 20px;'}
        %h1 Hello
        %label This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information
        = link_to "Learn More", "#", class: "btn btn-primary"
        %br/
        %br/
        %br/
      .col-md-3
        .create-your-free-account-box{style:"height: 200px;border: solid 2px #ddd; border-radius: 10px;"}
          %h3.form-title 
            = link_to "Create your Account", home_pricing_path
          = link_to "Sign up Now", home_pricing_path, class: 'btn btn-success col-xs-offset-3', :"data-no-turbolink"=>true, style:'margin-top: 40px;'
    %br/
    .row
      .col-md-9
        .row
          .col-md-6
            .video-box{style:'border: solid 2px #aaa; border-radius: 10px;background-color: #eee;'}
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              %br/
              
          .col-md-6
            %label 
              SiteAdmin
              This tool was created to keep on top the many different projects you have running and to help you keep focus on earning money instead of spending time doing things manually. 
            %br/
            %label  
              We want you to spend time making money and not creating new spreadsheets. Track your future projects and make them into live projects once you are ready. Track your monthly income and monthly orders to know if your having successful month. 
            %br/
            %label
              Track is also has simple project management feature where you can mange your future and existing niche projects. 
            %br/
            %label
              Fed up of using spreadsheets to trakli your ideas and income ? 
            %br/
            %label
              Welcome to trakli! trakli helps you managing your ideas,articles,income and expenses in one unified portal. 
              %br/
              One simple portal to manage your projects,tasks and keywords 
            %label  
              We know time is money this why we created a simple portal to save you time and best of all to help manage your online business better.
      .col-md-3
        %label "The best way to do that thing"
        %label "Dead simple whatever"
        %br/
        %br/
        %br/
        %br/
        %label "My WebApp is awesome - fast and easy"

- if current_user.present?
  #modal_edit_dashboard_charts.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog
      = form_for Option.new, url: home_set_option_path, method: :post, remote: false, html:{class: "form-horizontal edit_dashboard_charts"} do |f|
        = hidden_field_tag :rest_to_default, 0
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
            %h4#myModalLabel.modal-title Edit Dashboard Charts
          .modal-body.form-horizontal
            .container
              .col-sm-5
                %fieldset
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label                          
                          = check_box_tag "option[all_site_profit]", 'true', Option::option_value(current_user,"all_site_profit"), class: 'option-checkbox'
                          All Site Profit/Loss Chart
                          = hidden_field_tag "h_option[all_site_profit]", Option::option_value(current_user,"all_site_profit")
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label
                          = check_box_tag "option[top_earning]", 'true', Option::option_value(current_user,"top_earning"), class: 'option-checkbox'
                          Top Earning Sites
                          = hidden_field_tag "h_option[top_earning]", Option::option_value(current_user,"top_earning")                          
                      
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label
                          = check_box_tag "option[all_site_expenses]", 'true', Option::option_value(current_user,"all_site_expenses"), class: 'option-checkbox'
                          All Sites Expenses VS Earning
                          = hidden_field_tag "h_option[all_site_expenses]", Option::option_value(current_user,"all_site_expenses")
                          
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label                          
                          = check_box_tag "option[monthly_income_monthly_target]", 'true', Option::option_value(current_user,"monthly_income_monthly_target"), class: 'option-checkbox'
                          Monthly Income VS Monthly Target
                          = hidden_field_tag "h_option[monthly_income_monthly_target]", Option::option_value(current_user,"monthly_income_monthly_target")
                      
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label                          
                          = check_box_tag "option[last_year_current_year]", 'true', Option::option_value(current_user,"last_year_current_year"), class: 'option-checkbox'
                          Last Year VS Current Year
                          = hidden_field_tag "h_option[last_year_current_year]", Option::option_value(current_user,"last_year_current_year")
                  .form-group
                    .col-xs-offset-2.col-xs-10
                      .checkbox
                        %label
                          = check_box_tag "option[top_expenses]", 'true', Option::option_value(current_user,"top_expenses"), class: 'option-checkbox'                          
                          Top Expenses
                          = hidden_field_tag "h_option[top_expenses]", Option::option_value(current_user,"top_expenses")                          
          .modal-footer
            = f.submit "Apply", class: 'btn btn-primary'
            %button#rest_to_default_options.btn.btn-default{"data-dismiss" => "modal", type: "button"} Reset to Default



:javascript
  $(".option-checkbox").each(function(){
    $(this).click(function(){
      $("#h_"+$(this).attr("id")).val($(this).is(':checked'));
      $("#btn_save_merchang_list").removeClass("disabled").removeAttr("disabled");
    });
  });

  $("#rest_to_default_options").click(function(){
    $("#rest_to_default").val("1");
    $("#new_option").submit();
  });

app/views/home/pricing.html.haml
.row.chose-package-page
  .col-md-3.text-center.panel
    %h2 Max(Trial)
    %h4 $19.99/month
    %h4.object FOR LARGE TEAMS
    .blank
    %h5
      Up to
      %strong 20 Super Cool Thingies
    %h5 Unlimited This
    %h5 Unlimited That
    %h5 Unlimited The Other
    = link_to "Choose", new_registration_path(resource_name)+'?member=large', class: 'btn btn-danger', :"data-no-turbolink"=>true
    %br/
    %br/
  .col-md-3.text-center.panel
    %h2 Premium
    %h4 $29.99/month
    %h4.object FOR MEDIUM TEAMS
    .blank
    %h5
      Up to
      %strong 10 Super Cool Thingies
    %h5 Unlimited This
    %h5 Unlimited That
    %h5 Unlimited The Other
    = link_to "Choose", new_registration_path(resource_name)+'?member=medium', class: 'btn btn-danger', :"data-no-turbolink"=>true
    %br/
    %br/
  .col-md-3.text-center.panel
    %h2 Plus
    %h4 $49/month
    %h4.object PERFECT FOR MOST
    .blank
    %h5
      Up to
      %strong 5 Super Cool Thingies
    %h5 Unlimited This
    %h5 Unlimited That
    %h5 Unlimited The Other
    = link_to "Choose", new_registration_path(resource_name)+'?member=most', class: 'btn btn-danger', :"data-no-turbolink"=>true
    %br/
    %br/
  .col-md-3.text-center.panel
    %h2 Individual
    %h4 $79/month
    %h4.object FOR ONE PERSON
    .blank
    %h5
      %strong 1 Super Cool Thingy
    %h5 Unlimited This
    %h5 Unlimited That
    %h5 Unlimited The Other
    = link_to "Choose", new_registration_path(resource_name)+'?member=person', class: 'btn btn-danger', :"data-no-turbolink"=>true
    %br/
    %br/
.blank
.blank
.blank
.row
  %h5
    Enterprises: Need more than 20 Super Cool Thingies?
    %a{href: "#"} Contact Sales
/ /.container

:css
  .pricing{background-color: #444}